import { Building2, CalendarDays, CircleAlert, PhilippinePeso, Users, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, StatCard, StatsGrid, money } from '../components/ui'
import { roomSummary } from '../domain/filterRecords'
import { useAppStore } from '../store/AppStore'

export function DashboardPage(){const store=useAppStore();const rooms=roomSummary(store.units);const overdue=store.payments.filter(p=>p.status==='Overdue').reduce((sum,p)=>sum+p.amount,0);const openMaintenance=store.maintenance.filter(m=>m.status!=='Completed');const upcoming=store.viewings.filter(v=>v.status==='Scheduled');return <><PageHeader eyebrow="Daily workspace" title="What needs attention today?" copy="Start with viewings, tenant accounts, payments, or unit concerns from one connected workspace."/><div className="quick-actions"><Quick to="/viewings" icon={<CalendarDays/>} title="Manage viewings" copy={`${upcoming.length} scheduled`}/><Quick to="/tenants" icon={<Users/>} title="Find a tenant" copy={`${store.tenants.length} profiles`}/><Quick to="/payments" icon={<PhilippinePeso/>} title="Record payment" copy={`${money(overdue)} overdue`}/><Quick to="/maintenance" icon={<Wrench/>} title="Add maintenance" copy={`${openMaintenance.length} open items`}/></div><StatsGrid><StatCard label="Condominium units" value={store.units.length} icon={<Building2 size={17}/>} note={`${store.units.filter(u=>u.status==='Occupied').length} currently occupied`}/><StatCard label="Room capacity" value={rooms.capacity} icon={<Users size={17}/>} note={`${rooms.available} available spaces`}/><StatCard label="Active contracts" value={store.leases.filter(l=>l.status==='Active').length} icon={<PhilippinePeso size={17}/>} note={`${store.leases.filter(l=>l.status==='Expiring').length} expiring`}/><StatCard label="Open maintenance" value={openMaintenance.length} icon={<Wrench size={17}/>} note={`${openMaintenance.filter(m=>m.priority==='Urgent').length} urgent`}/></StatsGrid><div className="dashboard-grid"><section className="panel"><div className="section-head"><div><h2>Unit occupancy</h2><p>Current room-level distribution</p></div><Link className="text-link" to="/units">Open units</Link></div><div className="occupancy"><div className="donut-wrap"><div className="donut"/><div className="donut-label"><strong>{rooms.occupants}</strong>people</div></div><div className="legend"><Legend color="#19756f" label="Assigned occupants" value={rooms.occupants}/><Legend color="#2676aa" label="Available spaces" value={rooms.available}/><Legend color="#d8e0e6" label="Total capacity" value={rooms.capacity}/></div></div></section><section className="panel"><div className="section-head"><div><h2>Needs attention</h2><p>Plain-language follow-up list</p></div></div><div className="activity-list"><Activity icon={<CircleAlert size={15}/>} text={`${money(overdue)} in overdue rent`} time={`${store.payments.filter(p=>p.status==='Overdue').length} payment record(s)`}/><Activity icon={<Wrench size={15}/>} text={`${openMaintenance.length} maintenance items still open`} time="Review payer and evidence"/><Activity icon={<CalendarDays size={15}/>} text={`${upcoming.length} upcoming viewing(s)`} time="Confirm through Messenger"/></div></section></div></>}
function Quick({to,icon,title,copy}:{to:string;icon:React.ReactNode;title:string;copy:string}){return <Link className="quick-action" to={to}><span>{icon}</span><div><strong>{title}</strong><small>{copy}</small></div></Link>}
function Legend({color,label,value}:{color:string;label:string;value:number}){return <div className="legend-row"><span className="dot" style={{background:color}}/><span>{label}</span><strong>{value}</strong></div>}
function Activity({icon,text,time}:{icon:React.ReactNode;text:string;time:string}){return <div className="activity"><div className="activity-icon">{icon}</div><div><p>{text}</p><time>{time}</time></div></div>}
