import { CircleAlert, Clock3, FileText, PhilippinePeso, Plus, Users, Wrench } from 'lucide-react'
import { useMemo, useState } from 'react'
import { TenantAssignmentDialog } from '../components/TenantAssignmentDialog'
import { Badge, EmptyState, money, PageHeader, StatCard, StatsGrid } from '../components/ui'
import { leases, maintenance, payments } from '../data/mockData'
import type { Tenant } from '../domain/types'
import { useAppStore } from '../store/AppStore'

type Kind='tenants'|'leases'|'payments'|'maintenance'
const config={tenants:{eyebrow:'Resident records',title:'Tenants & occupants',copy:'Manage renters and the rooms or units assigned to them.',action:'Add tenant'},leases:{eyebrow:'Contract records',title:'Leases',copy:'Monitor whole-unit and room-level agreements.',action:'Create lease'},payments:{eyebrow:'Collection records',title:'Payments',copy:'Track room rent, received payments, and overdue balances.',action:'Record payment'},maintenance:{eyebrow:'Property operations',title:'Maintenance',copy:'Follow concerns from reporting through completion.',action:'New request'}}

export function RecordsPage({kind}:{kind:Kind}){
  const {units,tenants,assignTenant,addTenantToRoom}=useAppStore()
  const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [assigning,setAssigning]=useState<string|null>(null)
  const records=kind==='tenants'?tenants:kind==='leases'?leases:kind==='payments'?payments:maintenance
  const visible=useMemo(()=>records.filter(record=>(!search||JSON.stringify(record).toLowerCase().includes(search.toLowerCase()))&&(!status||record.status===status)),[records,search,status])
  const statuses=[...new Set(records.map(record=>record.status))];const c=config[kind]
  return <><PageHeader {...c} action={<button className="primary" onClick={()=>kind==='tenants'&&setAssigning('new')}><Plus size={16}/> {c.action}</button>}/><StatsGrid>{stats(kind,tenants)}</StatsGrid><section className="panel table-panel"><div className="section-head"><div><h2>{c.title} directory</h2><p>{kind==='tenants'?'Assignments here also update the Units page.':'Frontend demonstration data'}</p></div><span className="result-count">{visible.length} results</span></div><div className="toolbar"><input aria-label={`Search ${kind}`} placeholder={`Search ${kind}...`} value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter by status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map(value=><option key={value}>{value}</option>)}</select><button className="secondary" onClick={()=>{setSearch('');setStatus('')}}>Clear</button></div>{visible.length?<div className="table-wrap"><table><thead><tr>{headers(kind).map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{visible.map(record=><tr key={record.id}>{cells(kind,record,()=>setAssigning(record.id)).map((cell,index)=><td key={index}>{cell}</td>)}</tr>)}</tbody></table></div>:<EmptyState/>}</section>{kind==='tenants'&&assigning&&<TenantAssignmentDialog units={units} tenants={tenants} initialTenantId={assigning==='new'?'':assigning} defaultToNew={assigning==='new'} onAssign={assignTenant} onCreate={addTenantToRoom} onClose={()=>setAssigning(null)}/>}</>
}

function stats(kind:Kind,tenants:Tenant[]){if(kind==='tenants')return <><StatCard label="Profiles" value={tenants.length} icon={<Users size={17}/>} note="Primary account holders"/><StatCard label="Active" value={tenants.filter(t=>t.status==='Active').length} icon={<Users size={17}/>} note="Currently renting"/><StatCard label="Pending" value={tenants.filter(t=>t.status==='Pending').length} icon={<Clock3 size={17}/>} note="Upcoming move-in"/><StatCard label="Outstanding" value={money(tenants.reduce((sum,t)=>sum+t.balance,0))} icon={<CircleAlert size={17}/>} note="Across accounts"/></>;if(kind==='leases')return <><StatCard label="All leases" value={leases.length} icon={<FileText size={17}/>} note="Current register"/><StatCard label="Active" value={2} icon={<FileText size={17}/>} note="In force"/><StatCard label="Expiring" value={1} icon={<Clock3 size={17}/>} note="Within 90 days"/><StatCard label="Monthly rent" value={money(leases.reduce((sum,lease)=>sum+lease.rate,0))} icon={<PhilippinePeso size={17}/>} note="Contracted total"/></>;if(kind==='payments')return <><StatCard label="Expected" value={payments.length} icon={<PhilippinePeso size={17}/>} note="Current cycle"/><StatCard label="Collected" value={money(46000)} icon={<PhilippinePeso size={17}/>} note="Marked paid"/><StatCard label="Overdue" value={money(23000)} icon={<CircleAlert size={17}/>} note="Needs follow-up"/><StatCard label="Pending" value={money(22000)} icon={<Clock3 size={17}/>} note="Upcoming"/></>;return <><StatCard label="All requests" value={maintenance.length} icon={<Wrench size={17}/>} note="Current records"/><StatCard label="Open" value={1} icon={<CircleAlert size={17}/>} note="Needs assignment"/><StatCard label="Scheduled" value={1} icon={<Clock3 size={17}/>} note="Work arranged"/><StatCard label="Completed" value={1} icon={<Wrench size={17}/>} note="Closed request"/></>}
function headers(kind:Kind){return kind==='tenants'?['Tenant','Unit / room','Move-in','Balance','Status','Assignment']:kind==='leases'?['Tenant / unit','Start','End','Monthly rent','Status']:kind==='payments'?['Reference','Tenant / unit','Due','Amount','Status']:['Ticket','Unit','Issue','Reported','Priority','Status']}
function cells(kind:Kind,record:any,onAssign:()=>void):React.ReactNode[]{if(kind==='tenants')return [<><strong>{record.name}</strong><span className="subtext">{record.contact}</span></>,<>{record.unit||'Not assigned'}<span className="subtext">{record.room}</span></>,record.moveIn,record.balance?money(record.balance):'—',<Badge value={record.status}/>,<button className="secondary compact" onClick={onAssign}>Assign / move</button>];if(kind==='leases')return [<><strong>{record.tenant}</strong><span className="subtext">{record.unit}</span></>,record.start,record.end,money(record.rate),<Badge value={record.status}/>];if(kind==='payments')return [<strong>{record.reference}</strong>,<>{record.tenant}<span className="subtext">{record.unit}</span></>,record.due,money(record.amount),<Badge value={record.status}/>];return [<strong>{record.ticket}</strong>,record.unit,record.issue,record.reported,<Badge value={record.priority}/>,<Badge value={record.status}/>]}
