import { CircleAlert, Clock3, FileText, PhilippinePeso, Plus, Users, Wrench } from 'lucide-react'
import { useMemo, useState } from 'react'
import { leases, maintenance, payments, tenants } from '../data/mockData'
import { Badge, EmptyState, money, PageHeader, StatCard, StatsGrid } from '../components/ui'

type Kind='tenants'|'leases'|'payments'|'maintenance'
const config={tenants:{eyebrow:'Resident records',title:'Tenants & occupants',copy:'Manage renters and the rooms or units assigned to them.',action:'Add tenant'},leases:{eyebrow:'Contract records',title:'Leases',copy:'Monitor whole-unit and room-level agreements.',action:'Create lease'},payments:{eyebrow:'Collection records',title:'Payments',copy:'Track room rent, received payments, and overdue balances.',action:'Record payment'},maintenance:{eyebrow:'Property operations',title:'Maintenance',copy:'Follow concerns from reporting through completion.',action:'New request'}}
export function RecordsPage({kind}:{kind:Kind}){const [search,setSearch]=useState('');const [status,setStatus]=useState('');const records=kind==='tenants'?tenants:kind==='leases'?leases:kind==='payments'?payments:maintenance;const visible=useMemo(()=>records.filter(r=>(!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase()))&&(!status||r.status===status)),[records,search,status]);const statuses=[...new Set(records.map(r=>r.status))];const c=config[kind];return <><PageHeader {...c} action={<button className="primary"><Plus size={16}/> {c.action}</button>}/><StatsGrid>{stats(kind)}</StatsGrid><section className="panel table-panel"><div className="section-head"><div><h2>{c.title} directory</h2><p>Frontend demonstration data</p></div><span className="result-count">{visible.length} results</span></div><div className="toolbar"><input aria-label={`Search ${kind}`} placeholder={`Search ${kind}...`} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="secondary" onClick={()=>{setSearch('');setStatus('')}}>Clear</button></div>{visible.length?<div className="table-wrap"><table><thead><tr>{headers(kind).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(record=><tr key={record.id}>{cells(kind,record).map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>:<EmptyState/>}</section></>}
function stats(kind:Kind){if(kind==='tenants')return <><StatCard label="Profiles" value={tenants.length} icon={<Users size={17}/>} note="Primary account holders"/><StatCard label="Active" value={tenants.filter(t=>t.status==='Active').length} icon={<Users size={17}/>} note="Currently renting"/><StatCard label="Pending" value={1} icon={<Clock3 size={17}/>} note="Upcoming move-in"/><StatCard label="Outstanding" value={money(60000)} icon={<CircleAlert size={17}/>} note="Across accounts"/></>;if(kind==='leases')return <><StatCard label="All leases" value={leases.length} icon={<FileText size={17}/>} note="Current register"/><StatCard label="Active" value={2} icon={<FileText size={17}/>} note="In force"/><StatCard label="Expiring" value={1} icon={<Clock3 size={17}/>} note="Within 90 days"/><StatCard label="Monthly rent" value={money(leases.reduce((s,l)=>s+l.rate,0))} icon={<PhilippinePeso size={17}/>} note="Contracted total"/></>;if(kind==='payments')return <><StatCard label="Expected" value={payments.length} icon={<PhilippinePeso size={17}/>} note="Current cycle"/><StatCard label="Collected" value={money(46000)} icon={<PhilippinePeso size={17}/>} note="Marked paid"/><StatCard label="Overdue" value={money(23000)} icon={<CircleAlert size={17}/>} note="Needs follow-up"/><StatCard label="Pending" value={money(22000)} icon={<Clock3 size={17}/>} note="Upcoming"/></>;return <><StatCard label="All requests" value={maintenance.length} icon={<Wrench size={17}/>} note="Current records"/><StatCard label="Open" value={1} icon={<CircleAlert size={17}/>} note="Needs assignment"/><StatCard label="Scheduled" value={1} icon={<Clock3 size={17}/>} note="Work arranged"/><StatCard label="Completed" value={1} icon={<Wrench size={17}/>} note="Closed request"/></>}
function headers(kind:Kind){return kind==='tenants'?['Tenant','Unit / room','Move-in','Balance','Status']:kind==='leases'?['Tenant / unit','Start','End','Monthly rent','Status']:kind==='payments'?['Reference','Tenant / unit','Due','Amount','Status']:['Ticket','Unit','Issue','Reported','Priority','Status']}
function cells(kind:Kind,r:any):React.ReactNode[]{if(kind==='tenants')return [<><strong>{r.name}</strong><span className="subtext">{r.contact}</span></>,<>{r.unit}<span className="subtext">{r.room}</span></>,r.moveIn,r.balance?money(r.balance):'—',<Badge value={r.status}/>];if(kind==='leases')return [<><strong>{r.tenant}</strong><span className="subtext">{r.unit}</span></>,r.start,r.end,money(r.rate),<Badge value={r.status}/>];if(kind==='payments')return [<strong>{r.reference}</strong>,<>{r.tenant}<span className="subtext">{r.unit}</span></>,r.due,money(r.amount),<Badge value={r.status}/>];return [<strong>{r.ticket}</strong>,r.unit,r.issue,r.reported,<Badge value={r.priority}/>,<Badge value={r.status}/>]}
