import { CircleAlert, Clock3, FileText, PhilippinePeso, Plus, Upload, Users, Wrench } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { LeaseDialog, MaintenanceDialog, PaymentDialog } from '../components/RecordDialogs'
import { TenantAssignmentDialog } from '../components/TenantAssignmentDialog'
import { Badge, EmptyState, money, PageHeader, StatCard, StatsGrid } from '../components/ui'
import { useAppStore } from '../store/AppStore'

type Kind='tenants'|'leases'|'payments'|'maintenance'
const config={tenants:{eyebrow:'Resident records',title:'Tenants & occupants',copy:'Open one tenant to see their room, contract, payments, deposit, and maintenance.',action:'Add tenant'},leases:{eyebrow:'Contract records',title:'Contracts',copy:'Keep the printable template and signed contract details together.',action:'Record contract'},payments:{eyebrow:'Bank transfer records',title:'Payments',copy:'Record rent transfers and Messenger screenshots as payment proof.',action:'Record payment'},maintenance:{eyebrow:'Unit expenses',title:'Maintenance',copy:'Track repairs and decide whether the owner, deposit, or both pay.',action:'New expense'}}

export function RecordsPage({kind}:{kind:Kind}){const store=useAppStore();const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [dialog,setDialog]=useState<string|null>(null);const records=kind==='tenants'?store.tenants:kind==='leases'?store.leases:kind==='payments'?store.payments:store.maintenance;const visible=useMemo(()=>records.filter(record=>(!search||JSON.stringify(record).toLowerCase().includes(search.toLowerCase()))&&(!status||record.status===status)),[records,search,status]);const statuses=[...new Set(records.map(record=>record.status))];const c=config[kind];return <><PageHeader {...c} action={<button className="primary" onClick={()=>setDialog(kind==='tenants'?'new':kind)}><Plus size={16}/> {c.action}</button>}/><StatsGrid>{stats(kind,store)}</StatsGrid>{kind==='leases'&&<section className="template-strip"><div><FileText size={20}/><div><strong>Printable contract template</strong><span>{store.contractTemplate.name} · updated {store.contractTemplate.updatedAt}</span></div></div><label className="secondary upload-button"><Upload size={15}/> Replace template<input type="file" accept=".doc,.docx,.pdf" onChange={e=>e.target.files?.[0]&&store.updateContractTemplate(e.target.files[0].name)}/></label></section>}<section className="panel table-panel"><div className="section-head"><div><h2>{c.title} directory</h2><p>Connected frontend demonstration records</p></div><span className="result-count">{visible.length} results</span></div><div className="toolbar"><input aria-label={`Search ${kind}`} placeholder={`Search ${kind}...`} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(value=><option key={value}>{value}</option>)}</select><button className="secondary" onClick={()=>{setSearch('');setStatus('')}}>Clear</button></div>{visible.length?<div className="table-wrap"><table><thead><tr>{headers(kind).map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{visible.map(record=><tr key={record.id}>{cells(kind,record,()=>setDialog(record.id)).map((cell,index)=><td key={index}>{cell}</td>)}</tr>)}</tbody></table></div>:<EmptyState/>}</section>{kind==='tenants'&&dialog&&<TenantAssignmentDialog units={store.units} tenants={store.tenants} initialTenantId={dialog==='new'?'':dialog} defaultToNew={dialog==='new'} onAssign={store.assignTenant} onCreate={store.addTenantToRoom} onClose={()=>setDialog(null)}/>} {dialog==='leases'&&<LeaseDialog tenants={store.tenants} onSave={store.saveLease} onClose={()=>setDialog(null)}/>} {dialog==='payments'&&<PaymentDialog tenants={store.tenants} onSave={store.addPayment} onClose={()=>setDialog(null)}/>} {dialog==='maintenance'&&<MaintenanceDialog units={store.units} tenants={store.tenants} onSave={store.addMaintenance} onClose={()=>setDialog(null)}/>}</>}

function stats(kind:Kind,store:ReturnType<typeof useAppStore>){if(kind==='tenants')return <><StatCard label="Profiles" value={store.tenants.length} icon={<Users size={17}/>} note="All tenant records"/><StatCard label="Active" value={store.tenants.filter(t=>t.status==='Active').length} icon={<Users size={17}/>} note="Currently renting"/><StatCard label="Pending" value={store.tenants.filter(t=>t.status==='Pending').length} icon={<Clock3 size={17}/>} note="Upcoming move-in"/><StatCard label="Deposits held" value={money(store.tenants.reduce((sum,t)=>sum+t.deposit,0))} icon={<PhilippinePeso size={17}/>} note="Before deductions"/></>;if(kind==='leases')return <><StatCard label="Contracts" value={store.leases.length} icon={<FileText size={17}/>} note="Current register"/><StatCard label="Active" value={store.leases.filter(l=>l.status==='Active').length} icon={<FileText size={17}/>} note="In force"/><StatCard label="Expiring" value={store.leases.filter(l=>l.status==='Expiring').length} icon={<Clock3 size={17}/>} note="Needs follow-up"/><StatCard label="Monthly rent" value={money(store.leases.filter(l=>l.status!=='Ended').reduce((sum,l)=>sum+l.rate,0))} icon={<PhilippinePeso size={17}/>} note="Contracted total"/></>;if(kind==='payments')return <><StatCard label="Records" value={store.payments.length} icon={<PhilippinePeso size={17}/>} note="All billing periods"/><StatCard label="Collected" value={money(store.payments.filter(p=>p.status==='Paid').reduce((s,p)=>s+p.amount,0))} icon={<PhilippinePeso size={17}/>} note="Marked paid"/><StatCard label="Overdue" value={money(store.payments.filter(p=>p.status==='Overdue').reduce((s,p)=>s+p.amount,0))} icon={<CircleAlert size={17}/>} note="Needs follow-up"/><StatCard label="With proof" value={store.payments.filter(p=>p.proofName).length} icon={<FileText size={17}/>} note="Screenshot recorded"/></>;return <><StatCard label="Expenses" value={store.maintenance.length} icon={<Wrench size={17}/>} note="Maintenance records"/><StatCard label="Open" value={store.maintenance.filter(m=>m.status==='Open').length} icon={<CircleAlert size={17}/>} note="Needs action"/><StatCard label="Total cost" value={money(store.maintenance.reduce((s,m)=>s+m.amount,0))} icon={<PhilippinePeso size={17}/>} note="All allocations"/><StatCard label="Deposit use" value={money(store.depositEntries.reduce((s,d)=>s+d.amount,0))} icon={<Users size={17}/>} note="Explicit deductions"/></>}
function headers(kind:Kind){return kind==='tenants'?['Tenant','Unit / room','Move-in','Deposit','Status','Actions']:kind==='leases'?['Tenant / unit','Agreement','Monthly rent','Files','Status']:kind==='payments'?['Tenant / period','Transfer','Amount','Proof','Status']:['Ticket / unit','Work','Allocation','Cost','Evidence','Status']}
function cells(kind:Kind,r:any,onAssign:()=>void):React.ReactNode[]{if(kind==='tenants')return [<><strong>{r.name}</strong><span className="subtext">{r.contact}</span></>,<>{r.unit}<span className="subtext">{r.room}</span></>,r.moveIn,money(r.deposit),<Badge value={r.status}/>,<div className="row-actions"><Link className="text-link" to={`/tenants/${r.id}`}>Open profile</Link><button className="secondary compact" onClick={onAssign}>Assign / move</button></div>];if(kind==='leases')return [<><strong>{r.tenant}</strong><span className="subtext">{r.unit}</span></>,<>{r.start}<span className="subtext">to {r.end}</span></>,money(r.rate),r.signedCopyName?<><strong>Signed copy</strong><span className="subtext">{r.signedCopyName}</span></>:'Not attached',<Badge value={r.status}/>];if(kind==='payments')return [<><strong>{r.tenant}</strong><span className="subtext">{r.billingPeriod} · {r.unit}</span></>,<>{r.reference}<span className="subtext">{r.transferDate||`Due ${r.due}`}</span></>,money(r.amount),r.proofName||'No screenshot',<Badge value={r.status}/>];return [<><strong>{r.ticket}</strong><span className="subtext">{r.unit}</span></>,<>{r.category}<span className="subtext">{r.issue}</span></>,<Badge value={r.payer}/>,money(r.amount),r.evidenceName||'No file',<Badge value={r.status}/>]}
