import { BedDouble, Building2, Plus, RotateCcw, Users } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Badge, EmptyState, money, PageHeader, StatCard, StatsGrid } from '../components/ui'
import { TenantAssignmentDialog } from '../components/TenantAssignmentDialog'
import { filterRecords, roomSummary } from '../domain/filterRecords'
import type { RoomType, Unit } from '../domain/types'
import { useAppStore } from '../store/AppStore'

const roomTypes:RoomType[]=['Large','Medium','Small','Studio','Custom']
export function UnitsPage(){
  const {units,tenants,addRoom,assignTenant,addTenantToRoom,resetDemo}=useAppStore();const [filters,setFilters]=useState({search:'',status:'',property:'',roomType:''});const [selected,setSelected]=useState<Unit|null>(null);const [assigningUnit,setAssigningUnit]=useState<Unit|null>(null)
  const visible=useMemo(()=>filterRecords(units,filters),[units,filters]);const totals=roomSummary(units);const properties=[...new Set(units.map(u=>u.property))]
  return <>
    <PageHeader eyebrow="Property records" title="Units & room layouts" copy="Manage whole units and customize the rooms, capacity, rates, and occupants inside each one." action={<button className="primary" onClick={()=>setSelected(units[0])}><Plus size={16}/> Add room</button>}/>
    <StatsGrid><StatCard label="Condominium units" value={units.length} icon={<Building2 size={17}/>} note={`${properties.length} properties`}/><StatCard label="Rooms" value={totals.rooms} icon={<BedDouble size={17}/>} note="Across all layouts"/><StatCard label="Total capacity" value={totals.capacity} icon={<Users size={17}/>} note={`${totals.occupants} assigned occupants`}/><StatCard label="Available spaces" value={totals.available} icon={<Plus size={17}/>} note="Across shared and vacant rooms"/></StatsGrid>
    <section className="panel table-panel"><div className="section-head"><div><h2>Unit inventory</h2><p>Configure whole-unit or room-by-room rentals</p></div><span className="result-count">{visible.length} {visible.length===1?'result':'results'}</span></div>
      <div className="toolbar unit-toolbar"><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Search unit, room, or occupant..." aria-label="Search units"/><Select label="All statuses" value={filters.status} values={['Occupied','Vacant','Reserved']} onChange={status=>setFilters({...filters,status})}/><Select label="All properties" value={filters.property} values={properties} onChange={property=>setFilters({...filters,property})}/><Select label="All room types" value={filters.roomType} values={roomTypes} onChange={roomType=>setFilters({...filters,roomType})}/><button className="secondary" onClick={()=>setFilters({search:'',status:'',property:'',roomType:''})}>Clear</button></div>
      {visible.length?<div className="unit-card-grid">{visible.map(unit=><UnitCard key={unit.id} unit={unit} onConfigure={()=>setSelected(unit)} onAssign={()=>setAssigningUnit(unit)}/>)}</div>:<EmptyState/>}
    </section>
    <button className="reset-demo" onClick={resetDemo}><RotateCcw size={14}/> Reset demo data</button>
    {selected&&<RoomDialog unit={selected} onClose={()=>setSelected(null)} onSave={(room)=>{addRoom(selected.id,room);setSelected(null)}}/>}
    {assigningUnit&&<TenantAssignmentDialog units={units} tenants={tenants} initialUnitId={assigningUnit.id} onAssign={assignTenant} onCreate={addTenantToRoom} onClose={()=>setAssigningUnit(null)}/>}
  </>
}
function Select({label,value,values,onChange}:{label:string;value:string;values:readonly string[];onChange:(value:string)=>void}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">{label}</option>{values.map(v=><option key={v}>{v}</option>)}</select>}
function UnitCard({unit,onConfigure,onAssign}:{unit:Unit;onConfigure:()=>void;onAssign:()=>void}){const summary=roomSummary([unit]);return <article className="unit-card"><div className="unit-card-head"><div><span className="unit-code">{unit.code}</span><span>{unit.property}</span></div><Badge value={unit.status}/></div><div className="unit-card-meta"><span>{unit.layout}</span><strong>{summary.occupants}/{summary.capacity} occupied</strong></div><div className="room-list">{unit.rooms.map(room=><div className="room-row" key={room.id}><div><strong>{room.name}</strong><span>{room.type} · {room.occupants.length}/{room.capacity} people</span></div><span>{money(room.rate)}</span></div>)}</div><div className="unit-card-foot"><strong>{money(unit.monthlyRate)} <span>/ month</span></strong><div className="card-actions"><button className="secondary" onClick={onConfigure}>Rooms</button><button className="primary compact" onClick={onAssign}>Assign tenant</button></div></div></article>}
function RoomDialog({unit,onClose,onSave}:{unit:Unit;onClose:()=>void;onSave:(room:{name:string;type:RoomType;capacity:number;rate:number;occupants:string[]})=>void}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);onSave({name:String(form.get('name')),type:String(form.get('type')) as RoomType,capacity:Number(form.get('capacity')),rate:Number(form.get('rate')),occupants:String(form.get('occupants')).split(',').map(v=>v.trim()).filter(Boolean)})};return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="room-title"><form onSubmit={submit}><div className="dialog-head"><div><p className="eyebrow">Unit configuration</p><h2 id="room-title">Add room to {unit.code}</h2></div><button type="button" className="icon-button close-dialog" onClick={onClose} aria-label="Close">×</button></div><div className="form-grid"><label>Room name<input name="name" required autoFocus placeholder="e.g. Large Room A"/></label><label>Room type<select name="type">{roomTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Capacity<input name="capacity" type="number" min="1" max="20" defaultValue="1" required/></label><label>Monthly rate<input name="rate" type="number" min="0" step="500" defaultValue="0" required/></label></div><label>Current occupants<input name="occupants" placeholder="Names separated by commas"/></label><p className="form-help">Changes are saved in this browser for the frontend demonstration.</p><div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" type="submit">Add room</button></div></form></div></div>}
