import { useState, type FormEvent } from 'react'
import { roomRateForTenant } from '../domain/roomLayout'
import type { Lease, Tenant } from '../domain/types'
import { useAppStore } from '../store/AppStore'

const fileName=(form:FormData,key:string)=>{const file=form.get(key);return file instanceof File&&file.size?file.name:''}

export function LeaseDialog({tenants,onClose,onSave}:{tenants:Tenant[];onClose:()=>void;onSave:(input:Omit<Lease,'id'|'tenant'|'unit'>)=>void}){
  const {units}=useAppStore()
  const [tenantId,setTenantId]=useState(tenants[0]?.id||'')
  const tenant=tenants.find(record=>record.id===tenantId)
  const defaultRate=tenant?roomRateForTenant(units,tenant):0
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({tenantId,start:String(form.get('start')),end:String(form.get('end')),rate:Number(form.get('rate')),deposit:Number(form.get('deposit')),initialPayment:Number(form.get('initialPayment')),signedCopyName:fileName(form,'signedCopy')||undefined,status:String(form.get('status')) as Lease['status']});onClose()}
  return <div className="modal-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label="Record tenant contract"><div className="modal-shell"><div className="dialog-head"><div><p className="eyebrow">Agreement details</p><h2>Record tenant contract</h2></div><button className="icon-button close-dialog" onClick={onClose} aria-label="Close">×</button></div><form onSubmit={submit}><div className="form-grid"><label>Tenant<select name="tenantId" required value={tenantId} onChange={event=>setTenantId(event.target.value)}>{tenants.map(record=><option key={record.id} value={record.id}>{record.name} · {record.unit} · {record.room}</option>)}</select></label><label>Contract status<select name="status"><option>Draft</option><option>Active</option><option>Pending</option><option>Expiring</option><option>Ended</option></select></label><label>Start date<input name="start" type="date" required/></label><label>End date<input name="end" type="date" required/></label><label>Agreed monthly rate<input key={tenantId} name="rate" type="number" min="0" defaultValue={defaultRate} required/><small className="field-hint">Room default: {defaultRate.toLocaleString('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0})} per occupant</small></label><label>Security deposit<input name="deposit" type="number" min="0" required/></label><label>Initial amount paid<input name="initialPayment" type="number" min="0" required/></label><label>Signed contract copy<input name="signedCopy" type="file" accept="image/*,.pdf"/></label></div><div className="notice-box">The room rate is the normal price. Change the agreed rate and contract dates here for two-month stays, internships, or any special arrangement.</div><p className="form-help">Prototype note: only the selected filename is remembered in this browser. The real file will require backend storage.</p><div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save contract</button></div></form></div></div></div>
}
