import { createAndAssignTenant } from './occupancy'
import type { AppData, ExpensePayer, Maintenance } from './types'

export function tenantAccountSummary(data:AppData,tenantId:string){const records=data.payments.filter(payment=>payment.tenantId===tenantId);return records.reduce((summary,payment)=>{summary.total+=payment.amount;if(payment.status==='Paid')summary.paid+=payment.amount;else if(payment.status==='Overdue')summary.overdue+=payment.amount;else summary.pending+=payment.amount;return summary},{paid:0,pending:0,overdue:0,total:0})}

export function depositSummary(data:AppData,tenantId:string){const original=data.tenants.find(tenant=>tenant.id===tenantId)?.deposit||0;const deductions=data.depositEntries.filter(entry=>entry.tenantId===tenantId).reduce((sum,entry)=>sum+entry.amount,0);return {original,deductions,remaining:Math.max(0,original-deductions)}}

export function convertViewing(data:AppData,viewingId:string,assignment:{unitId:string;roomId:string;moveIn:string}):AppData{const viewing=data.viewings.find(record=>record.id===viewingId);if(!viewing)throw new Error('Viewing was not found.');const assigned=createAndAssignTenant(data.units,data.tenants,{name:viewing.prospectName,contact:viewing.contact,moveIn:assignment.moveIn,unitId:assignment.unitId,roomId:assignment.roomId});return {...data,...assigned,viewings:data.viewings.map(record=>record.id===viewingId?{...record,status:'Converted' as const}:record)}}

export interface MaintenanceExpenseInput {unitId:string;tenantId?:string;category:string;description:string;date:string;amount:number;tenantShare:number;payer:ExpensePayer;evidenceName:string}
export function recordMaintenanceExpense(data:AppData,input:MaintenanceExpenseInput):AppData{const unit=data.units.find(record=>record.id===input.unitId);if(!unit)throw new Error('Unit was not found.');if(input.tenantShare>input.amount)throw new Error('The tenant share cannot exceed the total expense.');if(input.tenantShare>0&&!input.tenantId)throw new Error('Choose the affected tenant.');if(input.tenantId&&input.tenantShare>depositSummary(data,input.tenantId).remaining)throw new Error('The deduction is higher than the remaining deposit.');const id=crypto.randomUUID();const record:Maintenance={id,ticket:`MNT-${String(data.maintenance.length+1043)}`,unitId:unit.id,unit:unit.code,tenantId:input.tenantId,issue:input.description,category:input.category,reported:input.date,amount:input.amount,tenantShare:input.tenantShare,payer:input.payer,evidenceName:input.evidenceName||undefined,priority:'Normal',status:'Open'};return {...data,maintenance:[record,...data.maintenance],depositEntries:input.tenantId&&input.tenantShare>0?[{id:crypto.randomUUID(),tenantId:input.tenantId,maintenanceId:id,date:input.date,description:input.description,amount:input.tenantShare,evidenceName:input.evidenceName||undefined},...data.depositEntries]:data.depositEntries}}
